// ポケモンのタイプ定義
const POKEMON_TYPES = {
    normal: { id: 1, name: "ノーマル", color: "#A8A878" },
    fighting: { id: 2, name: "かくとう", color: "#C03028" },
    flying: { id: 3, name: "ひこう", color: "#A890F0" },
    poison: { id: 4, name: "どく", color: "#A040A0" },
    ground: { id: 5, name: "じめん", color: "#E0C068" },
    rock: { id: 6, name: "いわ", color: "#B8A038" },
    bug: { id: 7, name: "むし", color: "#A8B820" },
    ghost: { id: 8, name: "ゴースト", color: "#705898" },
    steel: { id: 9, name: "はがね", color: "#B8B8D0" },
    fire: { id: 10, name: "ほのお", color: "#F08030" },
    water: { id: 11, name: "みず", color: "#6890F0" },
    grass: { id: 12, name: "くさ", color: "#78C850" },
    electric: { id: 13, name: "でんき", color: "#F8D030" },
    psychic: { id: 14, name: "エスパー", color: "#F85888" },
    ice: { id: 15, name: "こおり", color: "#98D8D8" },
    dragon: { id: 16, name: "ドラゴン", color: "#7038F8" },
    dark: { id: 17, name: "あく", color: "#705848" },
    fairy: { id: 18, name: "フェアリー", color: "#EE99AC" }
};

// 完全なポケモンリスト（タイプ情報付き）
const allPokemonList = [
    // 第1世代（カントー地方）
    { id: 1, name: "フシギダネ", types: ["grass", "poison"] },
    { id: 2, name: "フシギソウ", types: ["grass", "poison"] },
    { id: 3, name: "フシギバナ", types: ["grass", "poison"] },
    { id: 4, name: "ヒトカゲ", types: ["fire"] },
    { id: 5, name: "リザード", types: ["fire"] },
    { id: 6, name: "リザードン", types: ["fire", "flying"] },
    { id: 7, name: "ゼニガメ", types: ["water"] },
    { id: 8, name: "カメール", types: ["water"] },
    { id: 9, name: "カメックス", types: ["water"] },
    { id: 10, name: "キャタピー", types: ["bug"] },
    { id: 11, name: "トランセル", types: ["bug"] },
    { id: 12, name: "バタフリー", types: ["bug", "flying"] },
    { id: 13, name: "ビードル", types: ["bug", "poison"] },
    { id: 14, name: "コクーン", types: ["bug", "poison"] },
    { id: 15, name: "スピアー", types: ["bug", "poison"] },
    { id: 16, name: "ポッポ", types: ["normal", "flying"] },
    { id: 17, name: "ピジョン", types: ["normal", "flying"] },
    { id: 18, name: "ピジョット", types: ["normal", "flying"] },
    { id: 19, name: "コラッタ", types: ["normal"] },
    { id: 20, name: "ラッタ", types: ["normal"] },
    { id: 21, name: "オニスズメ", types: ["normal", "flying"] },
    { id: 22, name: "オニドリル", types: ["normal", "flying"] },
    { id: 23, name: "アーボ", types: ["poison"] },
    { id: 24, name: "アーボック", types: ["poison"] },
    { id: 25, name: "ピカチュウ", types: ["electric"] },
    { id: 26, name: "ライチュウ", types: ["electric"] },
    { id: 27, name: "サンド", types: ["ground"] },
    { id: 28, name: "サンドパン", types: ["ground"] },
    { id: 29, name: "ニドラン♀", types: ["poison"] },
    { id: 30, name: "ニドリーナ", types: ["poison"] },
    { id: 31, name: "ニドクイン", types: ["poison", "ground"] },
    { id: 32, name: "ニドラン♂", types: ["poison"] },
    { id: 33, name: "ニドリーノ", types: ["poison"] },
    { id: 34, name: "ニドキング", types: ["poison", "ground"] },
    { id: 35, name: "ピッピ", types: ["fairy"] },
    { id: 36, name: "ピクシー", types: ["fairy"] },
    { id: 37, name: "ロコン", types: ["fire"] },
    { id: 38, name: "キュウコン", types: ["fire"] },
    { id: 39, name: "プリン", types: ["normal", "fairy"] },
    { id: 40, name: "プクリン", types: ["normal", "fairy"] },
    { id: 41, name: "ズバット", types: ["poison", "flying"] },
    { id: 42, name: "ゴルバット", types: ["poison", "flying"] },
    { id: 43, name: "ナゾノクサ", types: ["grass", "poison"] },
    { id: 44, name: "クサイハナ", types: ["grass", "poison"] },
    { id: 45, name: "ラフレシア", types: ["grass", "poison"] },
    { id: 46, name: "パラス", types: ["bug", "grass"] },
    { id: 47, name: "パラセクト", types: ["bug", "grass"] },
    { id: 48, name: "コンパン", types: ["bug", "poison"] },
    { id: 49, name: "モルフォン", types: ["bug", "poison"] },
    { id: 50, name: "ディグダ", types: ["ground"] },
    { id: 51, name: "ダグトリオ", types: ["ground"] },
    { id: 52, name: "ニャース", types: ["normal"] },
    { id: 53, name: "ペルシアン", types: ["normal"] },
    { id: 54, name: "コダック", types: ["water"] },
    { id: 55, name: "ゴルダック", types: ["water"] },
    { id: 56, name: "マンキー", types: ["fighting"] },
    { id: 57, name: "オコリザル", types: ["fighting"] },
    { id: 58, name: "ガーディ", types: ["fire"] },
    { id: 59, name: "ウインディ", types: ["fire"] },
    { id: 60, name: "ニョロモ", types: ["water"] },
    { id: 61, name: "ニョロゾ", types: ["water"] },
    { id: 62, name: "ニョロボン", types: ["water", "fighting"] },
    { id: 63, name: "ケーシィ", types: ["psychic"] },
    { id: 64, name: "ユンゲラー", types: ["psychic"] },
    { id: 65, name: "フーディン", types: ["psychic"] },
    { id: 66, name: "ワンリキー", types: ["fighting"] },
    { id: 67, name: "ゴーリキー", types: ["fighting"] },
    { id: 68, name: "カイリキー", types: ["fighting"] },
    { id: 69, name: "マダツボミ", types: ["grass", "poison"] },
    { id: 70, name: "ウツドン", types: ["grass", "poison"] },
    { id: 71, name: "ウツボット", types: ["grass", "poison"] },
    { id: 72, name: "メノクラゲ", types: ["water", "poison"] },
    { id: 73, name: "ドククラゲ", types: ["water", "poison"] },
    { id: 74, name: "イシツブテ", types: ["rock", "ground"] },
    { id: 75, name: "ゴローン", types: ["rock", "ground"] },
    { id: 76, name: "ゴローニャ", types: ["rock", "ground"] },
    { id: 77, name: "ポニータ", types: ["fire"] },
    { id: 78, name: "ギャロップ", types: ["fire"] },
    { id: 79, name: "ヤドン", types: ["water", "psychic"] },
    { id: 80, name: "ヤドラン", types: ["water", "psychic"] },
    { id: 81, name: "コイル", types: ["electric", "steel"] },
    { id: 82, name: "レアコイル", types: ["electric", "steel"] },
    { id: 83, name: "カモネギ", types: ["normal", "flying"] },
    { id: 84, name: "ドードー", types: ["normal", "flying"] },
    { id: 85, name: "ドードリオ", types: ["normal", "flying"] },
    { id: 86, name: "パウワウ", types: ["water"] },
    { id: 87, name: "ジュゴン", types: ["water", "ice"] },
    { id: 88, name: "ベトベター", types: ["poison"] },
    { id: 89, name: "ベトベトン", types: ["poison"] },
    { id: 90, name: "シェルダー", types: ["water"] },
    { id: 91, name: "パルシェン", types: ["water", "ice"] },
    { id: 92, name: "ゴース", types: ["ghost", "poison"] },
    { id: 93, name: "ゴースト", types: ["ghost", "poison"] },
    { id: 94, name: "ゲンガー", types: ["ghost", "poison"] },
    { id: 95, name: "イワーク", types: ["rock", "ground"] },
    { id: 96, name: "スリープ", types: ["psychic"] },
    { id: 97, name: "スリーパー", types: ["psychic"] },
    { id: 98, name: "クラブ", types: ["water"] },
    { id: 99, name: "キングラー", types: ["water"] },
    { id: 100, name: "ビリリダマ", types: ["electric"] },
    { id: 101, name: "マルマイン", types: ["electric"] },
    { id: 102, name: "タマタマ", types: ["grass", "psychic"] },
    { id: 103, name: "ナッシー", types: ["grass", "psychic"] },
    { id: 104, name: "カラカラ", types: ["ground"] },
    { id: 105, name: "ガラガラ", types: ["ground"] },
    { id: 106, name: "サワムラー", types: ["fighting"] },
    { id: 107, name: "エビワラー", types: ["fighting"] },
    { id: 108, name: "ベロリンガ", types: ["normal"] },
    { id: 109, name: "ドガース", types: ["poison"] },
    { id: 110, name: "マタドガス", types: ["poison"] },
    { id: 111, name: "サイホーン", types: ["ground", "rock"] },
    { id: 112, name: "サイドン", types: ["ground", "rock"] },
    { id: 113, name: "ラッキー", types: ["normal"] },
    { id: 114, name: "モンジャラ", types: ["grass"] },
    { id: 115, name: "ガルーラ", types: ["normal"] },
    { id: 116, name: "タッツー", types: ["water"] },
    { id: 117, name: "シードラ", types: ["water"] },
    { id: 118, name: "トサキント", types: ["water"] },
    { id: 119, name: "アズマオウ", types: ["water"] },
    { id: 120, name: "ヒトデマン", types: ["water"] },
    { id: 121, name: "スターミー", types: ["water", "psychic"] },
    { id: 122, name: "バリヤード", types: ["psychic", "fairy"] },
    { id: 123, name: "ストライク", types: ["bug", "flying"] },
    { id: 124, name: "ルージュラ", types: ["ice", "psychic"] },
    { id: 125, name: "エレブー", types: ["electric"] },
    { id: 126, name: "ブーバー", types: ["fire"] },
    { id: 127, name: "カイロス", types: ["bug"] },
    { id: 128, name: "ケンタロス", types: ["normal"] },
    { id: 129, name: "コイキング", types: ["water"] },
    { id: 130, name: "ギャラドス", types: ["water", "flying"] },
    { id: 131, name: "ラプラス", types: ["water", "ice"] },
    { id: 132, name: "メタモン", types: ["normal"] },
    { id: 133, name: "イーブイ", types: ["normal"] },
    { id: 134, name: "シャワーズ", types: ["water"] },
    { id: 135, name: "サンダース", types: ["electric"] },
    { id: 136, name: "ブースター", types: ["fire"] },
    { id: 137, name: "ポリゴン", types: ["normal"] },
    { id: 138, name: "オムナイト", types: ["rock", "water"] },
    { id: 139, name: "オムスター", types: ["rock", "water"] },
    { id: 140, name: "カブト", types: ["rock", "water"] },
    { id: 141, name: "カブトプス", types: ["rock", "water"] },
    { id: 142, name: "プテラ", types: ["rock", "flying"] },
    { id: 143, name: "カビゴン", types: ["normal"] },
    { id: 144, name: "フリーザー", types: ["ice", "flying"] },
    { id: 145, name: "サンダー", types: ["electric", "flying"] },
    { id: 146, name: "ファイヤー", types: ["fire", "flying"] },
    { id: 147, name: "ミニリュウ", types: ["dragon"] },
    { id: 148, name: "ハクリュー", types: ["dragon"] },
    { id: 149, name: "カイリュー", types: ["dragon", "flying"] },
    { id: 150, name: "ミュウツー", types: ["psychic"] },
    { id: 151, name: "ミュウ", types: ["psychic"] },

    // 第2世代（ジョウト地方）
    { id: 152, name: "チコリータ", types: ["grass"] },
    { id: 153, name: "ベイリーフ", types: ["grass"] },
    { id: 154, name: "メガニウム", types: ["grass"] },
    { id: 155, name: "ヒノアラシ", types: ["fire"] },
    { id: 156, name: "マグマラシ", types: ["fire"] },
    { id: 157, name: "バクフーン", types: ["fire"] },
    { id: 158, name: "ワニノコ", types: ["water"] },
    { id: 159, name: "アリゲイツ", types: ["water"] },
    { id: 160, name: "オーダイル", types: ["water"] },
    { id: 161, name: "オタチ", types: ["normal"] },
    { id: 162, name: "オオタチ", types: ["normal"] },
    { id: 163, name: "ホーホー", types: ["normal", "flying"] },
    { id: 164, name: "ヨルノズク", types: ["normal", "flying"] },
    { id: 165, name: "レディバ", types: ["bug", "flying"] },
    { id: 166, name: "レディアン", types: ["bug", "flying"] },
    { id: 167, name: "イトマル", types: ["bug", "poison"] },
    { id: 168, name: "アリアドス", types: ["bug", "poison"] },
    { id: 169, name: "クロバット", types: ["poison", "flying"] },
    { id: 170, name: "チョンチー", types: ["water", "electric"] },
    { id: 171, name: "ランターン", types: ["water", "electric"] },
    { id: 172, name: "ピチュー", types: ["electric"] },
    { id: 173, name: "ピィ", types: ["fairy"] },
    { id: 174, name: "ププリン", types: ["normal", "fairy"] },
    { id: 175, name: "トゲピー", types: ["fairy"] },
    { id: 176, name: "トゲチック", types: ["fairy", "flying"] },
    { id: 177, name: "ネイティ", types: ["psychic", "flying"] },
    { id: 178, name: "ネイティオ", types: ["psychic", "flying"] },
    { id: 179, name: "メリープ", types: ["electric"] },
    { id: 180, name: "モココ", types: ["electric"] },
    { id: 181, name: "デンリュウ", types: ["electric"] },
    { id: 182, name: "キレイハナ", types: ["grass"] },
    { id: 183, name: "マリル", types: ["water", "fairy"] },
    { id: 184, name: "マリルリ", types: ["water", "fairy"] },
    { id: 185, name: "ウソッキー", types: ["rock"] },
    { id: 186, name: "ニョロトノ", types: ["water"] },
    { id: 187, name: "ハネッコ", types: ["grass", "flying"] },
    { id: 188, name: "ポポッコ", types: ["grass", "flying"] },
    { id: 189, name: "ワタッコ", types: ["grass", "flying"] },
    { id: 190, name: "エイパム", types: ["normal"] },
    { id: 191, name: "ヒマナッツ", types: ["grass"] },
    { id: 192, name: "キマワリ", types: ["grass"] },
    { id: 193, name: "ヤンヤンマ", types: ["bug", "flying"] },
    { id: 194, name: "ウパー", types: ["water", "ground"] },
    { id: 195, name: "ヌオー", types: ["water", "ground"] },
    { id: 196, name: "エーフィ", types: ["psychic"] },
    { id: 197, name: "ブラッキー", types: ["dark"] },
    { id: 198, name: "ヤミカラス", types: ["dark", "flying"] },
    { id: 199, name: "ヤドキング", types: ["water", "psychic"] },
    { id: 200, name: "ムウマ", types: ["ghost"] },
    { id: 201, name: "アンノーン", types: ["psychic"] },
    { id: 202, name: "ソーナンス", types: ["psychic"] },
    { id: 203, name: "キリンリキ", types: ["normal", "psychic"] },
    { id: 204, name: "クヌギダマ", types: ["bug"] },
    { id: 205, name: "フォレトス", types: ["bug", "steel"] },
    { id: 206, name: "ノコッチ", types: ["normal"] },
    { id: 207, name: "グライガー", types: ["ground", "flying"] },
    { id: 208, name: "ハガネール", types: ["steel", "ground"] },
    { id: 209, name: "ブルー", types: ["fairy"] },
    { id: 210, name: "グランブル", types: ["fairy"] },
    { id: 211, name: "ハリーセン", types: ["water", "poison"] },
    { id: 212, name: "ハッサム", types: ["bug", "steel"] },
    { id: 213, name: "ツボツボ", types: ["bug", "rock"] },
    { id: 214, name: "ヘラクロス", types: ["bug", "fighting"] },
    { id: 215, name: "ニューラ", types: ["dark", "ice"] },
    { id: 216, name: "ヒメグマ", types: ["normal"] },
    { id: 217, name: "リングマ", types: ["normal"] },
    { id: 218, name: "マグマッグ", types: ["fire"] },
    { id: 219, name: "マグカルゴ", types: ["fire", "rock"] },
    { id: 220, name: "ウリムー", types: ["ice", "ground"] },
    { id: 221, name: "イノムー", types: ["ice", "ground"] },
    { id: 222, name: "サニーゴ", types: ["water", "rock"] },
    { id: 223, name: "テッポウオ", types: ["water"] },
    { id: 224, name: "オクタン", types: ["water"] },
    { id: 225, name: "デリバード", types: ["ice", "flying"] },
    { id: 226, name: "マンタイン", types: ["water", "flying"] },
    { id: 227, name: "エアームド", types: ["steel", "flying"] },
    { id: 228, name: "デルビル", types: ["dark", "fire"] },
    { id: 229, name: "ヘルガー", types: ["dark", "fire"] },
    { id: 230, name: "キングドラ", types: ["water", "dragon"] },
    { id: 231, name: "ゴマゾウ", types: ["ground"] },
    { id: 232, name: "ドンファン", types: ["ground"] },
    { id: 233, name: "ポリゴン2", types: ["normal"] },
    { id: 234, name: "オドシシ", types: ["normal"] },
    { id: 235, name: "ドーブル", types: ["normal"] },
    { id: 236, name: "バルキー", types: ["fighting"] },
    { id: 237, name: "カポエラー", types: ["fighting"] },
    { id: 238, name: "ムチュール", types: ["ice", "psychic"] },
    { id: 239, name: "エレキッド", types: ["electric"] },
    { id: 240, name: "ブビィ", types: ["fire"] },
    { id: 241, name: "ミルタンク", types: ["normal"] },
    { id: 242, name: "ハピナス", types: ["normal"] },
    { id: 243, name: "ライコウ", types: ["electric"] },
    { id: 244, name: "エンテイ", types: ["fire"] },
    { id: 245, name: "スイクン", types: ["water"] },
    { id: 246, name: "ヨーギラス", types: ["rock", "ground"] },
    { id: 247, name: "サナギラス", types: ["rock", "ground"] },
    { id: 248, name: "バンギラス", types: ["rock", "dark"] },
    { id: 249, name: "ルギア", types: ["psychic", "flying"] },
    { id: 250, name: "ホウオウ", types: ["fire", "flying"] },
    { id: 251, name: "セレビィ", types: ["psychic", "grass"] },

    // 第3世代（ホウエン地方）
    { id: 252, name: "キモリ", types: ["grass"] },
    { id: 253, name: "ジュプトル", types: ["grass"] },
    { id: 254, name: "ジュカイン", types: ["grass"] },
    { id: 255, name: "アチャモ", types: ["fire"] },
    { id: 256, name: "ワカシャモ", types: ["fire", "fighting"] },
    { id: 257, name: "バシャーモ", types: ["fire", "fighting"] },
    { id: 258, name: "ミズゴロウ", types: ["water"] },
    { id: 259, name: "ヌマクロー", types: ["water", "ground"] },
    { id: 260, name: "ラグラージ", types: ["water", "ground"] },
    { id: 261, name: "ポチエナ", types: ["dark"] },
    { id: 262, name: "グラエナ", types: ["dark"] },
    { id: 263, name: "ジグザグマ", types: ["normal"] },
    { id: 264, name: "マッスグマ", types: ["normal"] },
    { id: 265, name: "ケムッソ", types: ["bug"] },
    { id: 266, name: "カラサリス", types: ["bug"] },
    { id: 267, name: "アゲハント", types: ["bug", "flying"] },
    { id: 268, name: "マユルド", types: ["bug"] },
    { id: 269, name: "ドクケイル", types: ["bug", "poison"] },
    { id: 270, name: "ハスボー", types: ["water", "grass"] },
    { id: 271, name: "ハスブレロ", types: ["water", "grass"] },
    { id: 272, name: "ルンパッパ", types: ["water", "grass"] },
    { id: 273, name: "タネボー", types: ["grass"] },
    { id: 274, name: "コノハナ", types: ["grass", "dark"] },
    { id: 275, name: "ダーテング", types: ["grass", "dark"] },
    { id: 276, name: "スバメ", types: ["normal", "flying"] },
    { id: 277, name: "オオスバメ", types: ["normal", "flying"] },
    { id: 278, name: "キャモメ", types: ["water", "flying"] },
    { id: 279, name: "ペリッパー", types: ["water", "flying"] },
    { id: 280, name: "ラルトス", types: ["psychic", "fairy"] },
    { id: 281, name: "キルリア", types: ["psychic", "fairy"] },
    { id: 282, name: "サーナイト", types: ["psychic", "fairy"] },
    { id: 283, name: "アメタマ", types: ["bug", "water"] },
    { id: 284, name: "アメモース", types: ["bug", "flying"] },
    { id: 285, name: "キノココ", types: ["grass"] },
    { id: 286, name: "キノガッサ", types: ["grass", "fighting"] },
    { id: 287, name: "ナマケロ", types: ["normal"] },
    { id: 288, name: "ヤルキモノ", types: ["normal"] },
    { id: 289, name: "ケッキング", types: ["normal"] },
    { id: 290, name: "ツチニン", types: ["bug", "ground"] },
    { id: 291, name: "テッカニン", types: ["bug", "flying"] },
    { id: 292, name: "ヌケニン", types: ["bug", "ghost"] },
    { id: 293, name: "ゴニョニョ", types: ["normal"] },
    { id: 294, name: "ドゴーム", types: ["normal"] },
    { id: 295, name: "バクオング", types: ["normal"] },
    { id: 296, name: "マクノシタ", types: ["fighting"] },
    { id: 297, name: "ハリテヤマ", types: ["fighting"] },
    { id: 298, name: "ルリリ", types: ["normal", "fairy"] },
    { id: 299, name: "ノズパス", types: ["rock"] },
    { id: 300, name: "エネコ", types: ["normal"] },
    { id: 301, name: "エネコロロ", types: ["normal"] },
    { id: 302, name: "ヤミラミ", types: ["dark", "ghost"] },
    { id: 303, name: "クチート", types: ["steel", "fairy"] },
    { id: 304, name: "ココドラ", types: ["steel", "rock"] },
    { id: 305, name: "コドラ", types: ["steel", "rock"] },
    { id: 306, name: "ボスゴドラ", types: ["steel", "rock"] },
    { id: 307, name: "アサナン", types: ["fighting", "psychic"] },
    { id: 308, name: "チャーレム", types: ["fighting", "psychic"] },
    { id: 309, name: "ラクライ", types: ["electric"] },
    { id: 310, name: "ライボルト", types: ["electric"] },
    { id: 311, name: "プラスル", types: ["electric"] },
    { id: 312, name: "マイナン", types: ["electric"] },
    { id: 313, name: "バルビート", types: ["bug"] },
    { id: 314, name: "イルミーゼ", types: ["bug"] },
    { id: 315, name: "ロゼリア", types: ["grass", "poison"] },
    { id: 316, name: "ゴクリン", types: ["poison"] },
    { id: 317, name: "マルノーム", types: ["poison"] },
    { id: 318, name: "キバニア", types: ["water", "dark"] },
    { id: 319, name: "サメハダー", types: ["water", "dark"] },
    { id: 320, name: "ホエルコ", types: ["water"] },
    { id: 321, name: "ホエルオー", types: ["water"] },
    { id: 322, name: "ドンメル", types: ["fire", "ground"] },
    { id: 323, name: "バクーダ", types: ["fire", "ground"] },
    { id: 324, name: "コータス", types: ["fire"] },
    { id: 325, name: "バネブー", types: ["psychic"] },
    { id: 326, name: "ブーピッグ", types: ["psychic"] },
    { id: 327, name: "パッチール", types: ["normal"] },
    { id: 328, name: "ナックラー", types: ["ground"] },
    { id: 329, name: "ビブラーバ", types: ["ground", "dragon"] },
    { id: 330, name: "フライゴン", types: ["ground", "dragon"] },
    { id: 331, name: "サボネア", types: ["grass"] },
    { id: 332, name: "ノクタス", types: ["grass", "dark"] },
    { id: 333, name: "チルット", types: ["normal", "flying"] },
    { id: 334, name: "チルタリス", types: ["dragon", "flying"] },
    { id: 335, name: "ザングース", types: ["normal"] },
    { id: 336, name: "ハブネーク", types: ["poison"] },
    { id: 337, name: "ルナトーン", types: ["rock", "psychic"] },
    { id: 338, name: "ソルロック", types: ["rock", "psychic"] },
    { id: 339, name: "ドジョッチ", types: ["water", "ground"] },
    { id: 340, name: "ナマズン", types: ["water", "ground"] },
    { id: 341, name: "ヘイガニ", types: ["water"] },
    { id: 342, name: "シザリガー", types: ["water", "dark"] },
    { id: 343, name: "ヤジロン", types: ["ground", "psychic"] },
    { id: 344, name: "ネンドール", types: ["ground", "psychic"] },
    { id: 345, name: "リリーラ", types: ["rock", "grass"] },
    { id: 346, name: "ユレイドル", types: ["rock", "grass"] },
    { id: 347, name: "アノプス", types: ["rock", "bug"] },
    { id: 348, name: "アーマルド", types: ["rock", "bug"] },
    { id: 349, name: "ヒンバス", types: ["water"] },
    { id: 350, name: "ミロカロス", types: ["water"] },
    { id: 351, name: "ポワルン", types: ["normal"] },
    { id: 352, name: "カクレオン", types: ["normal"] },
    { id: 353, name: "カゲボウズ", types: ["ghost"] },
    { id: 354, name: "ジュペッタ", types: ["ghost"] },
    { id: 355, name: "ヨマワル", types: ["ghost"] },
    { id: 356, name: "サマヨール", types: ["ghost"] },
    { id: 357, name: "トロピウス", types: ["grass", "flying"] },
    { id: 358, name: "チリーン", types: ["psychic"] },
    { id: 359, name: "アブソル", types: ["dark"] },
    { id: 360, name: "ソーナノ", types: ["psychic"] },
    { id: 361, name: "ユキワラシ", types: ["ice"] },
    { id: 362, name: "オニゴーリ", types: ["ice"] },
    { id: 363, name: "タマザラシ", types: ["ice", "water"] },
    { id: 364, name: "トドグラー", types: ["ice", "water"] },
    { id: 365, name: "トドゼルガ", types: ["ice", "water"] },
    { id: 366, name: "パールル", types: ["water"] },
    { id: 367, name: "ハンテール", types: ["water"] },
    { id: 368, name: "サクラビス", types: ["water"] },
    { id: 369, name: "ジーランス", types: ["water", "rock"] },
    { id: 370, name: "ラブカス", types: ["water"] },
    { id: 371, name: "タツベイ", types: ["dragon"] },
    { id: 372, name: "コモルー", types: ["dragon"] },
    { id: 373, name: "ボーマンダ", types: ["dragon", "flying"] },
    { id: 374, name: "ダンバル", types: ["steel", "psychic"] },
    { id: 375, name: "メタング", types: ["steel", "psychic"] },
    { id: 376, name: "メタグロス", types: ["steel", "psychic"] },
    { id: 377, name: "レジロック", types: ["rock"] },
    { id: 378, name: "レジアイス", types: ["ice"] },
    { id: 379, name: "レジスチル", types: ["steel"] },
    { id: 380, name: "ラティアス", types: ["dragon", "psychic"] },
    { id: 381, name: "ラティオス", types: ["dragon", "psychic"] },
    { id: 382, name: "カイオーガ", types: ["water"] },
    { id: 383, name: "グラードン", types: ["ground"] },
    { id: 384, name: "レックウザ", types: ["dragon", "flying"] },
    { id: 385, name: "ジラーチ", types: ["steel", "psychic"] },
    { id: 386, name: "デオキシス", types: ["psychic"] },

    // 第4世代（シンオウ地方）
    { id: 387, name: "ナエトル", types: ["grass"] },
    { id: 388, name: "ハヤシガメ", types: ["grass"] },
    { id: 389, name: "ドダイトス", types: ["grass", "ground"] },
    { id: 390, name: "ヒコザル", types: ["fire"] },
    { id: 391, name: "モウカザル", types: ["fire", "fighting"] },
    { id: 392, name: "ゴウカザル", types: ["fire", "fighting"] },
    { id: 393, name: "ポッチャマ", types: ["water"] },
    { id: 394, name: "ポッタイシ", types: ["water"] },
    { id: 395, name: "エンペルト", types: ["water", "steel"] },
    { id: 396, name: "ムックル", types: ["normal", "flying"] },
    { id: 397, name: "ムクバード", types: ["normal", "flying"] },
    { id: 398, name: "ムクホーク", types: ["normal", "flying"] },
    { id: 399, name: "ビッパ", types: ["normal"] },
    { id: 400, name: "ビーダル", types: ["normal", "water"] },
    { id: 401, name: "コロボーシ", types: ["bug"] },
    { id: 402, name: "コロトック", types: ["bug"] },
    { id: 403, name: "コリンク", types: ["electric"] },
    { id: 404, name: "ルクシオ", types: ["electric"] },
    { id: 405, name: "レントラー", types: ["electric"] },
    { id: 406, name: "スボミー", types: ["grass", "poison"] },
    { id: 407, name: "ロズレイド", types: ["grass", "poison"] },
    { id: 408, name: "ズガイドス", types: ["rock"] },
    { id: 409, name: "ラムパルド", types: ["rock"] },
    { id: 410, name: "タテトプス", types: ["rock", "steel"] },
    { id: 411, name: "トリデプス", types: ["rock", "steel"] },
    { id: 412, name: "ミノムッチ", types: ["bug"] },
    { id: 413, name: "ミノマダム", types: ["bug", "grass"] },
    { id: 414, name: "ガーメイル", types: ["bug", "flying"] },
    { id: 415, name: "ミツハニー", types: ["bug", "flying"] },
    { id: 416, name: "ビークイン", types: ["bug", "flying"] },
    { id: 417, name: "パチリス", types: ["electric"] },
    { id: 418, name: "ブイゼル", types: ["water"] },
    { id: 419, name: "フローゼル", types: ["water"] },
    { id: 420, name: "チェリンボ", types: ["grass"] },
    { id: 421, name: "チェリム", types: ["grass"] },
    { id: 422, name: "カラナクシ", types: ["water", "ground"] },
    { id: 423, name: "トリトドン", types: ["water", "ground"] },
    { id: 424, name: "エテボース", types: ["normal"] },
    { id: 425, name: "フワンテ", types: ["ghost", "flying"] },
    { id: 426, name: "フワライド", types: ["ghost", "flying"] },
    { id: 427, name: "ミミロル", types: ["normal"] },
    { id: 428, name: "ミミロップ", types: ["normal"] },
    { id: 429, name: "ムウマージ", types: ["ghost"] },
    { id: 430, name: "ドンカラス", types: ["dark", "flying"] },
    { id: 431, name: "ニャルマー", types: ["normal"] },
    { id: 432, name: "ブニャット", types: ["normal"] },
    { id: 433, name: "リーシャン", types: ["psychic"] },
    { id: 434, name: "スカンプー", types: ["poison", "dark"] },
    { id: 435, name: "スカタンク", types: ["poison", "dark"] },
    { id: 436, name: "ドーミラー", types: ["steel", "psychic"] },
    { id: 437, name: "ドータクン", types: ["steel", "psychic"] },
    { id: 438, name: "ウソハチ", types: ["rock"] },
    { id: 439, name: "マネネ", types: ["psychic", "fairy"] },
    { id: 440, name: "ピンプク", types: ["normal"] },
    { id: 441, name: "ペラップ", types: ["normal", "flying"] },
    { id: 442, name: "ミカルゲ", types: ["ghost", "dark"] },
    { id: 443, name: "フカマル", types: ["dragon", "ground"] },
    { id: 444, name: "ガバイト", types: ["dragon", "ground"] },
    { id: 445, name: "ガブリアス", types: ["dragon", "ground"] },
    { id: 446, name: "ゴンベ", types: ["normal"] },
    { id: 447, name: "リオル", types: ["fighting"] },
    { id: 448, name: "ルカリオ", types: ["fighting", "steel"] },
    { id: 449, name: "ヒポポタス", types: ["ground"] },
    { id: 450, name: "カバルドン", types: ["ground"] },
    { id: 451, name: "スコルピ", types: ["poison", "bug"] },
    { id: 452, name: "ドラピオン", types: ["poison", "dark"] },
    { id: 453, name: "グレッグル", types: ["poison", "fighting"] },
    { id: 454, name: "ドクロッグ", types: ["poison", "fighting"] },
    { id: 455, name: "マスキッパ", types: ["grass"] },
    { id: 456, name: "ケイコウオ", types: ["water"] },
    { id: 457, name: "ネオラント", types: ["water"] },
    { id: 458, name: "タマンタ", types: ["water", "flying"] },
    { id: 459, name: "ユキカブリ", types: ["grass", "ice"] },
    { id: 460, name: "ユキノオー", types: ["grass", "ice"] },
    { id: 461, name: "マニューラ", types: ["dark", "ice"] },
    { id: 462, name: "ジバコイル", types: ["electric", "steel"] },
    { id: 463, name: "ベロベルト", types: ["normal"] },
    { id: 464, name: "ドサイドン", types: ["ground", "rock"] },
    { id: 465, name: "モジャンボ", types: ["grass"] },
    { id: 466, name: "エレキブル", types: ["electric"] },
    { id: 467, name: "ブーバーン", types: ["fire"] },
    { id: 468, name: "トゲキッス", types: ["fairy", "flying"] },
    { id: 469, name: "メガヤンマ", types: ["bug", "flying"] },
    { id: 470, name: "リーフィア", types: ["grass"] },
    { id: 471, name: "グレイシア", types: ["ice"] },
    { id: 472, name: "グライオン", types: ["ground", "flying"] },
    { id: 473, name: "マンムー", types: ["ice", "ground"] },
    { id: 474, name: "ポリゴンZ", types: ["normal"] },
    { id: 475, name: "エルレイド", types: ["psychic", "fighting"] },
    { id: 476, name: "ダイノーズ", types: ["rock", "steel"] },
    { id: 477, name: "ヨノワール", types: ["ghost"] },
    { id: 478, name: "ユキメノコ", types: ["ice", "ghost"] },
    { id: 479, name: "ロトム", types: ["electric", "ghost"] },
    { id: 480, name: "ユクシー", types: ["psychic"] },
    { id: 481, name: "エムリット", types: ["psychic"] },
    { id: 482, name: "アグノム", types: ["psychic"] },
    { id: 483, name: "ディアルガ", types: ["steel", "dragon"] },
    { id: 484, name: "パルキア", types: ["water", "dragon"] },
    { id: 485, name: "ヒードラン", types: ["fire", "steel"] },
    { id: 486, name: "レジギガス", types: ["normal"] },
    { id: 487, name: "ギラティナ", types: ["ghost", "dragon"] },
    { id: 488, name: "クレセリア", types: ["psychic"] },
    { id: 489, name: "フィオネ", types: ["water"] },
    { id: 490, name: "マナフィ", types: ["water"] },
    { id: 491, name: "ダークライ", types: ["dark"] },
    { id: 492, name: "シェイミ", types: ["grass"] },
    { id: 493, name: "アルセウス", types: ["normal"] },

    // 第5世代（イッシュ地方）
    { id: 494, name: "ビクティニ", types: ["psychic", "fire"] },
    { id: 495, name: "ツタージャ", types: ["grass"] },
    { id: 496, name: "ジャノビー", types: ["grass"] },
    { id: 497, name: "ジャローダ", types: ["grass"] },
    { id: 498, name: "ポカブ", types: ["fire"] },
    { id: 499, name: "チャオブー", types: ["fire", "fighting"] },
    { id: 500, name: "エンブオー", types: ["fire", "fighting"] },
    { id: 501, name: "ミジュマル", types: ["water"] },
    { id: 502, name: "フタチマル", types: ["water"] },
    { id: 503, name: "ダイケンキ", types: ["water"] },
    { id: 504, name: "ミネズミ", types: ["normal"] },
    { id: 505, name: "ミルホッグ", types: ["normal"] },
    { id: 506, name: "ヨーテリー", types: ["normal"] },
    { id: 507, name: "ハーデリア", types: ["normal"] },
    { id: 508, name: "ムーランド", types: ["normal"] },
    { id: 509, name: "チョロネコ", types: ["dark"] },
    { id: 510, name: "レパルダス", types: ["dark"] },
    { id: 511, name: "ヤナップ", types: ["grass"] },
    { id: 512, name: "ヤナッキー", types: ["grass"] },
    { id: 513, name: "バオップ", types: ["fire"] },
    { id: 514, name: "バオッキー", types: ["fire"] },
    { id: 515, name: "ヒヤップ", types: ["water"] },
    { id: 516, name: "ヒヤッキー", types: ["water"] },
    { id: 517, name: "ムンナ", types: ["psychic"] },
    { id: 518, name: "ムシャーナ", types: ["psychic"] },
    { id: 519, name: "マメパト", types: ["normal", "flying"] },
    { id: 520, name: "ハトーボー", types: ["normal", "flying"] },
    { id: 521, name: "ケンホロウ", types: ["normal", "flying"] },
    { id: 522, name: "シママ", types: ["electric"] },
    { id: 523, name: "ゼブライカ", types: ["electric"] },
    { id: 524, name: "ダンゴロ", types: ["rock"] },
    { id: 525, name: "ガントル", types: ["rock"] },
    { id: 526, name: "ギガイアス", types: ["rock"] },
    { id: 527, name: "コロモリ", types: ["psychic", "flying"] },
    { id: 528, name: "ココロモリ", types: ["psychic", "flying"] },
    { id: 529, name: "モグリュー", types: ["ground"] },
    { id: 530, name: "ドリュウズ", types: ["ground", "steel"] },
    { id: 531, name: "タブンネ", types: ["normal"] },
    { id: 532, name: "ドッコラー", types: ["fighting"] },
    { id: 533, name: "ドテッコツ", types: ["fighting"] },
    { id: 534, name: "ローブシン", types: ["fighting"] },
    { id: 535, name: "オタマロ", types: ["water"] },
    { id: 536, name: "ガマガル", types: ["water", "ground"] },
    { id: 537, name: "ガマゲロゲ", types: ["water", "ground"] },
    { id: 538, name: "ナゲキ", types: ["fighting"] },
    { id: 539, name: "ダゲキ", types: ["fighting"] },
    { id: 540, name: "クルミル", types: ["bug", "grass"] },
    { id: 541, name: "クルマユ", types: ["bug", "grass"] },
    { id: 542, name: "ハハコモリ", types: ["bug", "grass"] },
    { id: 543, name: "フシデ", types: ["bug", "poison"] },
    { id: 544, name: "ホイーガ", types: ["bug", "poison"] },
    { id: 545, name: "ペンドラー", types: ["bug", "poison"] },
    { id: 546, name: "モンメン", types: ["grass", "fairy"] },
    { id: 547, name: "エルフーン", types: ["grass", "fairy"] },
    { id: 548, name: "チュリネ", types: ["grass"] },
    { id: 549, name: "ドレディア", types: ["grass"] },
    { id: 550, name: "バスラオ", types: ["water"] },
    { id: 551, name: "メグロコ", types: ["ground", "dark"] },
    { id: 552, name: "ワルビル", types: ["ground", "dark"] },
    { id: 553, name: "ワルビアル", types: ["ground", "dark"] },
    { id: 554, name: "ダルマッカ", types: ["fire"] },
    { id: 555, name: "ヒヒダルマ", types: ["fire"] },
    { id: 556, name: "マラカッチ", types: ["grass"] },
    { id: 557, name: "イシズマイ", types: ["bug", "rock"] },
    { id: 558, name: "イワパレス", types: ["bug", "rock"] },
    { id: 559, name: "ズルッグ", types: ["dark", "fighting"] },
    { id: 560, name: "ズルズキン", types: ["dark", "fighting"] },
    { id: 561, name: "シンボラー", types: ["psychic", "flying"] },
    { id: 562, name: "デスマス", types: ["ghost"] },
    { id: 563, name: "デスカーン", types: ["ghost"] },
    { id: 564, name: "プロトーガ", types: ["water", "rock"] },
    { id: 565, name: "アバゴーラ", types: ["water", "rock"] },
    { id: 566, name: "アーケン", types: ["rock", "flying"] },
    { id: 567, name: "アーケオス", types: ["rock", "flying"] },
    { id: 568, name: "ヤブクロン", types: ["poison"] },
    { id: 569, name: "ダストダス", types: ["poison"] },
    { id: 570, name: "ゾロア", types: ["dark"] },
    { id: 571, name: "ゾロアーク", types: ["dark"] },
    { id: 572, name: "チラーミィ", types: ["normal"] },
    { id: 573, name: "チラチーノ", types: ["normal"] },
    { id: 574, name: "ゴチム", types: ["psychic"] },
    { id: 575, name: "ゴチミル", types: ["psychic"] },
    { id: 576, name: "ゴチルゼル", types: ["psychic"] },
    { id: 577, name: "ユニラン", types: ["psychic"] },
    { id: 578, name: "ダブラン", types: ["psychic"] },
    { id: 579, name: "ランクルス", types: ["psychic"] },
    { id: 580, name: "コアルヒー", types: ["water", "flying"] },
    { id: 581, name: "スワンナ", types: ["water", "flying"] },
    { id: 582, name: "バニプッチ", types: ["ice"] },
    { id: 583, name: "バニリッチ", types: ["ice"] },
    { id: 584, name: "バイバニラ", types: ["ice"] },
    { id: 585, name: "シキジカ", types: ["normal", "grass"] },
    { id: 586, name: "メブキジカ", types: ["normal", "grass"] },
    { id: 587, name: "エモンガ", types: ["electric", "flying"] },
    { id: 588, name: "カブルモ", types: ["bug"] },
    { id: 589, name: "シュバルゴ", types: ["bug", "steel"] },
    { id: 590, name: "タマゲタケ", types: ["grass", "poison"] },
    { id: 591, name: "モロバレル", types: ["grass", "poison"] },
    { id: 592, name: "プルリル", types: ["water", "ghost"] },
    { id: 593, name: "ブルンゲル", types: ["water", "ghost"] },
    { id: 594, name: "ママンボウ", types: ["water"] },
    { id: 595, name: "バチュル", types: ["bug", "electric"] },
    { id: 596, name: "デンチュラ", types: ["bug", "electric"] },
    { id: 597, name: "テッシード", types: ["grass", "steel"] },
    { id: 598, name: "ナットレイ", types: ["grass", "steel"] },
    { id: 599, name: "ギアル", types: ["steel"] },
    { id: 600, name: "ギギアル", types: ["steel"] },
    { id: 601, name: "ギギギアル", types: ["steel"] },
    { id: 602, name: "シビシラス", types: ["electric"] },
    { id: 603, name: "シビビール", types: ["electric"] },
    { id: 604, name: "シビルドン", types: ["electric"] },
    { id: 605, name: "リグレー", types: ["psychic"] },
    { id: 606, name: "オーベム", types: ["psychic"] },
    { id: 607, name: "ヒトモシ", types: ["ghost", "fire"] },
    { id: 608, name: "ランプラー", types: ["ghost", "fire"] },
    { id: 609, name: "シャンデラ", types: ["ghost", "fire"] },
    { id: 610, name: "キバゴ", types: ["dragon"] },
    { id: 611, name: "オノンド", types: ["dragon"] },
    { id: 612, name: "オノノクス", types: ["dragon"] },
    { id: 613, name: "クマシュン", types: ["ice"] },
    { id: 614, name: "ツンベアー", types: ["ice"] },
    { id: 615, name: "フリージオ", types: ["ice"] },
    { id: 616, name: "チョボマキ", types: ["bug"] },
    { id: 617, name: "アギルダー", types: ["bug"] },
    { id: 618, name: "マッギョ", types: ["ground", "electric"] },
    { id: 619, name: "コジョフー", types: ["fighting"] },
    { id: 620, name: "コジョンド", types: ["fighting"] },
    { id: 621, name: "クリムガン", types: ["dragon"] },
    { id: 622, name: "ゴビット", types: ["ground", "ghost"] },
    { id: 623, name: "ゴルーグ", types: ["ground", "ghost"] },
    { id: 624, name: "コマタナ", types: ["dark", "steel"] },
    { id: 625, name: "キリキザン", types: ["dark", "steel"] },
    { id: 626, name: "バッフロン", types: ["normal"] },
    { id: 627, name: "ワシボン", types: ["normal", "flying"] },
    { id: 628, name: "ウォーグル", types: ["normal", "flying"] },
    { id: 629, name: "バルチャイ", types: ["dark", "flying"] },
    { id: 630, name: "バルジーナ", types: ["dark", "flying"] },
    { id: 631, name: "クイタラン", types: ["fire"] },
    { id: 632, name: "アイアント", types: ["bug", "steel"] },
    { id: 633, name: "モノズ", types: ["dark", "dragon"] },
    { id: 634, name: "ジヘッド", types: ["dark", "dragon"] },
    { id: 635, name: "サザンドラ", types: ["dark", "dragon"] },
    { id: 636, name: "メラルバ", types: ["bug", "fire"] },
    { id: 637, name: "ウルガモス", types: ["bug", "fire"] },
    { id: 638, name: "コバルオン", types: ["steel", "fighting"] },
    { id: 639, name: "テラキオン", types: ["rock", "fighting"] },
    { id: 640, name: "ビリジオン", types: ["grass", "fighting"] },
    { id: 641, name: "トルネロス", types: ["flying"] },
    { id: 642, name: "ボルトロス", types: ["electric", "flying"] },
    { id: 643, name: "レシラム", types: ["dragon", "fire"] },
    { id: 644, name: "ゼクロム", types: ["dragon", "electric"] },
    { id: 645, name: "ランドロス", types: ["ground", "flying"] },
    { id: 646, name: "キュレム", types: ["dragon", "ice"] },
    { id: 647, name: "ケルディオ", types: ["water", "fighting"] },
    { id: 648, name: "メロエッタ", types: ["normal", "psychic"] },
    { id: 649, name: "ゲノセクト", types: ["bug", "steel"] },

    // 第6世代（カロス地方）
    { id: 650, name: "ハリマロン", types: ["grass"] },
    { id: 651, name: "ハリボーグ", types: ["grass"] },
    { id: 652, name: "ブリガロン", types: ["grass", "fighting"] },
    { id: 653, name: "フォッコ", types: ["fire"] },
    { id: 654, name: "テールナー", types: ["fire"] },
    { id: 655, name: "マフォクシー", types: ["fire", "psychic"] },
    { id: 656, name: "ケロマツ", types: ["water"] },
    { id: 657, name: "ゲコガシラ", types: ["water"] },
    { id: 658, name: "ゲッコウガ", types: ["water", "dark"] },
    { id: 659, name: "ホルビー", types: ["normal"] },
    { id: 660, name: "ホルード", types: ["normal", "ground"] },
    { id: 661, name: "ヤヤコマ", types: ["normal", "flying"] },
    { id: 662, name: "ヒノヤコマ", types: ["fire", "flying"] },
    { id: 663, name: "ファイアロー", types: ["fire", "flying"] },
    { id: 664, name: "コフキムシ", types: ["bug"] },
    { id: 665, name: "コフーライ", types: ["bug"] },
    { id: 666, name: "ビビヨン", types: ["bug", "flying"] },
    { id: 667, name: "シシコ", types: ["fire", "normal"] },
    { id: 668, name: "カエンジシ", types: ["fire", "normal"] },
    { id: 669, name: "フラベベ", types: ["fairy"] },
    { id: 670, name: "フラエッテ", types: ["fairy"] },
    { id: 671, name: "フラージェス", types: ["fairy"] },
    { id: 672, name: "メェークル", types: ["grass"] },
    { id: 673, name: "ゴーゴート", types: ["grass"] },
    { id: 674, name: "ヤンチャム", types: ["fighting"] },
    { id: 675, name: "ゴロンダ", types: ["fighting", "dark"] },
    { id: 676, name: "トリミアン", types: ["normal"] },
    { id: 677, name: "ニャスパー", types: ["psychic"] },
    { id: 678, name: "ニャオニクス", types: ["psychic"] },
    { id: 679, name: "ヒトツキ", types: ["steel", "ghost"] },
    { id: 680, name: "ニダンギル", types: ["steel", "ghost"] },
    { id: 681, name: "ギルガルド", types: ["steel", "ghost"] },
    { id: 682, name: "シュシュプ", types: ["fairy"] },
    { id: 683, name: "フレフワン", types: ["fairy"] },
    { id: 684, name: "ペロッパフ", types: ["fairy"] },
    { id: 685, name: "ペロリーム", types: ["fairy"] },
    { id: 686, name: "マーイーカ", types: ["dark", "psychic"] },
    { id: 687, name: "カラマネロ", types: ["dark", "psychic"] },
    { id: 688, name: "カメテテ", types: ["rock", "water"] },
    { id: 689, name: "ガメノデス", types: ["rock", "water"] },
    { id: 690, name: "クズモー", types: ["poison", "water"] },
    { id: 691, name: "ドラミドロ", types: ["poison", "dragon"] },
    { id: 692, name: "ウデッポウ", types: ["water"] },
    { id: 693, name: "ブロスター", types: ["water"] },
    { id: 694, name: "エリキテル", types: ["electric", "normal"] },
    { id: 695, name: "エレザード", types: ["electric", "normal"] },
    { id: 696, name: "チゴラス", types: ["rock", "dragon"] },
    { id: 697, name: "ガチゴラス", types: ["rock", "dragon"] },
    { id: 698, name: "アマルス", types: ["rock", "ice"] },
    { id: 699, name: "アマルルガ", types: ["rock", "ice"] },
    { id: 700, name: "ニンフィア", types: ["fairy"] },
    { id: 701, name: "ルチャブル", types: ["fighting", "flying"] },
    { id: 702, name: "デデンネ", types: ["electric", "fairy"] },
    { id: 703, name: "メレシー", types: ["rock", "fairy"] },
    { id: 704, name: "ヌメラ", types: ["dragon"] },
    { id: 705, name: "ヌメイル", types: ["dragon"] },
    { id: 706, name: "ヌメルゴン", types: ["dragon"] },
    { id: 707, name: "クレッフィ", types: ["steel", "fairy"] },
    { id: 708, name: "ボクレー", types: ["ghost", "grass"] },
    { id: 709, name: "オーロット", types: ["ghost", "grass"] },
    { id: 710, name: "バケッチャ", types: ["ghost", "grass"] },
    { id: 711, name: "パンプジン", types: ["ghost", "grass"] },
    { id: 712, name: "カチコール", types: ["ice"] },
    { id: 713, name: "クレベース", types: ["ice"] },
    { id: 714, name: "オンバット", types: ["flying", "dragon"] },
    { id: 715, name: "オンバーン", types: ["flying", "dragon"] },
    { id: 716, name: "ゼルネアス", types: ["fairy"] },
    { id: 717, name: "イベルタル", types: ["dark", "flying"] },
    { id: 718, name: "ジガルデ", types: ["dragon", "ground"] },
    { id: 719, name: "ディアンシー", types: ["rock", "fairy"] },
    { id: 720, name: "フーパ", types: ["psychic", "ghost"] },
    { id: 721, name: "ボルケニオン", types: ["fire", "water"] },

    // 第7世代（アローラ地方）
    { id: 722, name: "モクロー", types: ["grass", "flying"] },
    { id: 723, name: "フクスロー", types: ["grass", "flying"] },
    { id: 724, name: "ジュナイパー", types: ["grass", "ghost"] },
    { id: 725, name: "ニャビー", types: ["fire"] },
    { id: 726, name: "ニャヒート", types: ["fire"] },
    { id: 727, name: "ガオガエン", types: ["fire", "dark"] },
    { id: 728, name: "アシマリ", types: ["water"] },
    { id: 729, name: "オシャマリ", types: ["water"] },
    { id: 730, name: "アシレーヌ", types: ["water", "fairy"] },
    { id: 731, name: "ツツケラ", types: ["normal", "flying"] },
    { id: 732, name: "ケララッパ", types: ["normal", "flying"] },
    { id: 733, name: "ドデカバシ", types: ["normal", "flying"] },
    { id: 734, name: "ヤングース", types: ["normal"] },
    { id: 735, name: "デカグース", types: ["normal"] },
    { id: 736, name: "アゴジムシ", types: ["bug"] },
    { id: 737, name: "デンヂムシ", types: ["bug", "electric"] },
    { id: 738, name: "クワガノン", types: ["bug", "electric"] },
    { id: 739, name: "マケンカニ", types: ["fighting"] },
    { id: 740, name: "ケケンカニ", types: ["fighting", "ice"] },
    { id: 741, name: "オドリドリ", types: ["fire", "flying"] },
    { id: 742, name: "アブリー", types: ["bug", "fairy"] },
    { id: 743, name: "アブリボン", types: ["bug", "fairy"] },
    { id: 744, name: "イワンコ", types: ["rock"] },
    { id: 745, name: "ルガルガン", types: ["rock"] },
    { id: 746, name: "ヨワシ", types: ["water"] },
    { id: 747, name: "ヒドイデ", types: ["poison", "water"] },
    { id: 748, name: "ドヒドイデ", types: ["poison", "water"] },
    { id: 749, name: "ドロバンコ", types: ["ground"] },
    { id: 750, name: "バンバドロ", types: ["ground"] },
    { id: 751, name: "シズクモ", types: ["water", "bug"] },
    { id: 752, name: "オニシズクモ", types: ["water", "bug"] },
    { id: 753, name: "カリキリ", types: ["grass"] },
    { id: 754, name: "ラランテス", types: ["grass"] },
    { id: 755, name: "ネマシュ", types: ["grass", "fairy"] },
    { id: 756, name: "マシェード", types: ["grass", "fairy"] },
    { id: 757, name: "ヤトウモリ", types: ["poison", "fire"] },
    { id: 758, name: "エンニュート", types: ["poison", "fire"] },
    { id: 759, name: "ヌイコグマ", types: ["normal", "fighting"] },
    { id: 760, name: "キテルグマ", types: ["normal", "fighting"] },
    { id: 761, name: "アマカジ", types: ["grass"] },
    { id: 762, name: "アママイコ", types: ["grass"] },
    { id: 763, name: "アマージョ", types: ["grass"] },
    { id: 764, name: "キュワワー", types: ["fairy"] },
    { id: 765, name: "ヤレユータン", types: ["normal", "psychic"] },
    { id: 766, name: "ナゲツケサル", types: ["fighting"] },
    { id: 767, name: "コソクムシ", types: ["bug", "water"] },
    { id: 768, name: "グソクムシャ", types: ["bug", "water"] },
    { id: 769, name: "スナバァ", types: ["ghost", "ground"] },
    { id: 770, name: "シロデスナ", types: ["ghost", "ground"] },
    { id: 771, name: "ナマコブシ", types: ["water"] },
    { id: 772, name: "タイプ:ヌル", types: ["normal"] },
    { id: 773, name: "シルヴァディ", types: ["normal"] },
    { id: 774, name: "メテノ", types: ["rock", "flying"] },
    { id: 775, name: "ネッコアラ", types: ["normal"] },
    { id: 776, name: "バクガメス", types: ["fire", "dragon"] },
    { id: 777, name: "トゲデマル", types: ["electric", "steel"] },
    { id: 778, name: "ミミッキュ", types: ["ghost", "fairy"] },
    { id: 779, name: "ハギギシリ", types: ["water", "psychic"] },
    { id: 780, name: "ジジーロン", types: ["normal", "dragon"] },
    { id: 781, name: "ダダリン", types: ["ghost", "grass"] },
    { id: 782, name: "ジャラコ", types: ["dragon"] },
    { id: 783, name: "ジャランゴ", types: ["dragon", "fighting"] },
    { id: 784, name: "ジャラランガ", types: ["dragon", "fighting"] },
    { id: 785, name: "カプ・コケコ", types: ["electric", "fairy"] },
    { id: 786, name: "カプ・テテフ", types: ["psychic", "fairy"] },
    { id: 787, name: "カプ・ブルル", types: ["grass", "fairy"] },
    { id: 788, name: "カプ・レヒレ", types: ["water", "fairy"] },
    { id: 789, name: "コスモッグ", types: ["psychic"] },
    { id: 790, name: "コスモウム", types: ["psychic"] },
    { id: 791, name: "ソルガレオ", types: ["psychic", "steel"] },
    { id: 792, name: "ルナアーラ", types: ["psychic", "ghost"] },
    { id: 793, name: "ウツロイド", types: ["rock", "poison"] },
    { id: 794, name: "マッシブーン", types: ["bug", "fighting"] },
    { id: 795, name: "フェローチェ", types: ["bug", "fighting"] },
    { id: 796, name: "デンジュモク", types: ["electric"] },
    { id: 797, name: "テッカグヤ", types: ["steel", "flying"] },
    { id: 798, name: "カミツルギ", types: ["grass", "steel"] },
    { id: 799, name: "アクジキング", types: ["dark", "dragon"] },
    { id: 800, name: "ネクロズマ", types: ["psychic"] },
    { id: 801, name: "マギアナ", types: ["steel", "fairy"] },
    { id: 802, name: "マーシャドー", types: ["fighting", "ghost"] },
    { id: 803, name: "ベベノム", types: ["poison", "dragon"] },
    { id: 804, name: "アーゴヨン", types: ["poison", "dragon"] },
    { id: 805, name: "ツンデツンデ", types: ["rock", "steel"] },
    { id: 806, name: "ズガドーン", types: ["fire", "ghost"] },
    { id: 807, name: "ゼラオラ", types: ["electric"] },
    { id: 808, name: "メルタン", types: ["steel"] },
    { id: 809, name: "メルメタル", types: ["steel"] },

    // 第8世代（ガラル地方）
    { id: 810, name: "サルノリ", types: ["grass"] },
    { id: 811, name: "バチンキー", types: ["grass"] },
    { id: 812, name: "ゴリランダー", types: ["grass"] },
    { id: 813, name: "ヒバニー", types: ["fire"] },
    { id: 814, name: "ラビフット", types: ["fire"] },
    { id: 815, name: "エースバーン", types: ["fire"] },
    { id: 816, name: "メッソン", types: ["water"] },
    { id: 817, name: "ジメレオン", types: ["water"] },
    { id: 818, name: "インテレオン", types: ["water"] },
    { id: 819, name: "ホシガリス", types: ["normal"] },
    { id: 820, name: "ヨクバリス", types: ["normal"] },
    { id: 821, name: "ココガラ", types: ["flying"] },
    { id: 822, name: "アオガラス", types: ["flying"] },
    { id: 823, name: "アーマーガア", types: ["flying", "steel"] },
    { id: 824, name: "サッチムシ", types: ["bug", "psychic"] },
    { id: 825, name: "レドームシ", types: ["bug", "psychic"] },
    { id: 826, name: "イオルブ", types: ["bug", "psychic"] },
    { id: 827, name: "クスネ", types: ["dark"] },
    { id: 828, name: "フォクスライ", types: ["dark"] },
    { id: 829, name: "ヒメンカ", types: ["grass"] },
    { id: 830, name: "ワタシラガ", types: ["grass"] },
    { id: 831, name: "ウールー", types: ["normal"] },
    { id: 832, name: "バイウールー", types: ["normal"] },
    { id: 833, name: "カムカメ", types: ["water"] },
    { id: 834, name: "カジリガメ", types: ["water", "rock"] },
    { id: 835, name: "ワンパチ", types: ["electric"] },
    { id: 836, name: "パルスワン", types: ["electric"] },
    { id: 837, name: "タンドン", types: ["rock"] },
    { id: 838, name: "トロッゴン", types: ["rock", "fire"] },
    { id: 839, name: "セキタンザン", types: ["rock", "fire"] },
    { id: 840, name: "カジッチュ", types: ["grass", "dragon"] },
    { id: 841, name: "アップリュー", types: ["grass", "dragon"] },
    { id: 842, name: "タルップル", types: ["grass", "dragon"] },
    { id: 843, name: "スナヘビ", types: ["ground"] },
    { id: 844, name: "サダイジャ", types: ["ground", "fire"] },
    { id: 845, name: "ウッウ", types: ["flying", "water"] },
    { id: 846, name: "サシカマス", types: ["water"] },
    { id: 847, name: "カマスジョー", types: ["water"] },
    { id: 848, name: "エレズン", types: ["poison", "electric"] },
    { id: 849, name: "ストリンダー", types: ["poison", "electric"] },
    { id: 850, name: "ヤクデ", types: ["fire", "bug"] },
    { id: 851, name: "マルヤクデ", types: ["fire", "bug"] },
    { id: 852, name: "タタッコ", types: ["fighting"] },
    { id: 853, name: "オトスパス", types: ["fighting"] },
    { id: 854, name: "ヤバチャ", types: ["ghost"] },
    { id: 855, name: "ポットデス", types: ["ghost"] },
    { id: 856, name: "ミブリム", types: ["psychic"] },
    { id: 857, name: "テブリム", types: ["psychic"] },
    { id: 858, name: "ブリムオン", types: ["psychic", "fairy"] },
    { id: 859, name: "ベロバー", types: ["dark", "fairy"] },
    { id: 860, name: "ギモー", types: ["dark", "fairy"] },
    { id: 861, name: "オーロンゲ", types: ["dark", "fairy"] },
    { id: 862, name: "タチフサグマ", types: ["dark", "normal"] },
    { id: 863, name: "ニャイキング", types: ["steel"] },
    { id: 864, name: "サニゴーン", types: ["ghost"] },
    { id: 865, name: "ネギガナイト", types: ["fighting"] },
    { id: 866, name: "バリコオル", types: ["ice", "psychic"] },
    { id: 867, name: "デスバーン", types: ["ground", "ghost"] },
    { id: 868, name: "マホミル", types: ["fairy"] },
    { id: 869, name: "マホイップ", types: ["fairy"] },
    { id: 870, name: "タイレーツ", types: ["fighting"] },
    { id: 871, name: "バチンウニ", types: ["electric"] },
    { id: 872, name: "ユキハミ", types: ["ice", "bug"] },
    { id: 873, name: "モスノウ", types: ["ice", "bug"] },
    { id: 874, name: "イシヘンジン", types: ["rock"] },
    { id: 875, name: "コオリッポ", types: ["ice"] },
    { id: 876, name: "イエッサン", types: ["normal", "psychic"] },
    { id: 877, name: "モルペコ", types: ["electric", "dark"] },
    { id: 878, name: "ゾウドウ", types: ["steel"] },
    { id: 879, name: "ダイオウドウ", types: ["steel"] },
    { id: 880, name: "パッチラゴン", types: ["electric", "dragon"] },
    { id: 881, name: "パッチルドン", types: ["electric", "ice"] },
    { id: 882, name: "ウオノラゴン", types: ["water", "dragon"] },
    { id: 883, name: "ウオチルドン", types: ["water", "ice"] },
    { id: 884, name: "ジュラルドン", types: ["steel", "dragon"] },
    { id: 885, name: "ドラメシヤ", types: ["dragon", "ghost"] },
    { id: 886, name: "ドロンチ", types: ["dragon", "ghost"] },
    { id: 887, name: "ドラパルト", types: ["dragon", "ghost"] },
    { id: 888, name: "ザシアン", types: ["fairy"] },
    { id: 889, name: "ザマゼンタ", types: ["fighting"] },
    { id: 890, name: "ムゲンダイナ", types: ["poison", "dragon"] },
    { id: 891, name: "ダクマ", types: ["fighting"] },
    { id: 892, name: "ウーラオス", types: ["fighting", "dark"] },
    { id: 893, name: "ザルード", types: ["dark", "grass"] },
    { id: 894, name: "レジエレキ", types: ["electric"] },
    { id: 895, name: "レジドラゴ", types: ["dragon"] },
    { id: 896, name: "ブリザポス", types: ["ice"] },
    { id: 897, name: "レイスポス", types: ["ghost"] },
    { id: 898, name: "バドレックス", types: ["psychic", "grass"] },

    // 第9世代（パルデア地方）
    { id: 906, name: "ニャオハ", types: ["grass"] },
    { id: 907, name: "ニャローテ", types: ["grass"] },
    { id: 908, name: "マスカーニャ", types: ["grass", "dark"] },
    { id: 909, name: "ホゲータ", types: ["fire"] },
    { id: 910, name: "アチゲータ", types: ["fire"] },
    { id: 911, name: "ラウドボーン", types: ["fire", "ghost"] },
    { id: 912, name: "クワッス", types: ["water"] },
    { id: 913, name: "ウェルカモ", types: ["water"] },
    { id: 914, name: "ウェーニバル", types: ["water", "fighting"] },
    { id: 915, name: "グルトン", types: ["normal"] },
    { id: 916, name: "パフュートン", types: ["normal"] },
    { id: 917, name: "タマンチュラ", types: ["bug"] },
    { id: 918, name: "ワナイダー", types: ["bug"] },
    { id: 919, name: "マメバッタ", types: ["bug"] },
    { id: 920, name: "エクスレッグ", types: ["bug", "dark"] },
    { id: 921, name: "パモ", types: ["electric"] },
    { id: 922, name: "パモット", types: ["electric"] },
    { id: 923, name: "パーモット", types: ["electric", "fighting"] },
    { id: 924, name: "ワッカネズミ", types: ["normal"] },
    { id: 925, name: "イッカネズミ", types: ["normal"] },
    { id: 926, name: "パピモッチ", types: ["fairy"] },
    { id: 927, name: "バウッツェル", types: ["fairy"] },
    { id: 928, name: "ミニーブ", types: ["grass", "normal"] },
    { id: 929, name: "オリーニョ", types: ["grass", "normal"] },
    { id: 930, name: "オリーヴァ", types: ["grass", "normal"] },
    { id: 931, name: "イキリンコ", types: ["normal", "flying"] },
    { id: 932, name: "コジオ", types: ["rock"] },
    { id: 933, name: "ジオヅム", types: ["rock"] },
    { id: 934, name: "キョジオーン", types: ["rock"] },
    { id: 935, name: "カルボウ", types: ["fire"] },
    { id: 936, name: "グレンアルマ", types: ["fire", "psychic"] },
    { id: 937, name: "ソウブレイズ", types: ["fire", "ghost"] },
    { id: 938, name: "ズピカ", types: ["electric"] },
    { id: 939, name: "ハラバリー", types: ["electric"] },
    { id: 940, name: "カイデン", types: ["water", "flying"] },
    { id: 941, name: "タイカイデン", types: ["water", "flying"] },
    { id: 942, name: "オラチフ", types: ["dark"] },
    { id: 943, name: "マフィティフ", types: ["dark"] },
    { id: 944, name: "シルシュルー", types: ["poison", "normal"] },
    { id: 945, name: "タギングル", types: ["poison", "normal"] },
    { id: 946, name: "アノクサ", types: ["grass", "ghost"] },
    { id: 947, name: "アノホラグサ", types: ["grass", "ghost"] },
    { id: 948, name: "ノノクラゲ", types: ["ground"] },
    { id: 949, name: "リククラゲ", types: ["ground"] },
    { id: 950, name: "ガケガニ", types: ["rock"] },
    { id: 951, name: "カプサイジ", types: ["grass", "fire"] },
    { id: 952, name: "スコヴィラン", types: ["grass", "fire"] },
    { id: 953, name: "シガロコ", types: ["normal"] },
    { id: 954, name: "ベラカス", types: ["normal"] },
    { id: 955, name: "ヒラヒナ", types: ["psychic"] },
    { id: 956, name: "クエスパトラ", types: ["psychic"] },
    { id: 957, name: "カヌチャン", types: ["fairy", "steel"] },
    { id: 958, name: "ナカヌチャン", types: ["fairy", "steel"] },
    { id: 959, name: "デカヌチャン", types: ["fairy", "steel"] },
    { id: 960, name: "ウミディグダ", types: ["ground"] },
    { id: 961, name: "ウミトリオ", types: ["ground"] },
    { id: 962, name: "オトシドリ", types: ["water", "flying"] },
    { id: 963, name: "ナミイルカ", types: ["water"] },
    { id: 964, name: "イルカマン", types: ["water"] },
    { id: 965, name: "ブロロン", types: ["poison", "steel"] },
    { id: 966, name: "ブロロローム", types: ["poison", "steel"] },
    { id: 967, name: "モトトカゲ", types: ["bug", "psychic"] },
    { id: 968, name: "ミミズズ", types: ["electric", "ground"] },
    { id: 969, name: "キラーメ", types: ["rock", "poison"] },
    { id: 970, name: "キラフロル", types: ["rock", "poison"] },
    { id: 971, name: "ボチ", types: ["ghost"] },
    { id: 972, name: "ハカドッグ", types: ["ghost"] },
    { id: 973, name: "カラミンゴ", types: ["fairy"] },
    { id: 974, name: "アルクジラ", types: ["ice"] },
    { id: 975, name: "ハルクジラ", types: ["ice"] },
    { id: 976, name: "ミガルーサ", types: ["water", "psychic"] },
    { id: 977, name: "ヘイラッシャ", types: ["water"] },
    { id: 978, name: "シャリタツ", types: ["dragon", "water"] },
    { id: 979, name: "コノヨザル", types: ["fighting", "ghost"] },
    { id: 980, name: "ドオー", types: ["poison", "ground"] },
    { id: 981, name: "リキキリン", types: ["normal", "psychic"] },
    { id: 982, name: "ノココッチ", types: ["normal"] },
    { id: 983, name: "ドドゲザン", types: ["dark", "steel"] },
    { id: 984, name: "イダイナキバ", types: ["ground", "fighting"] },
    { id: 985, name: "サケブシッポ", types: ["ghost", "fire"] },
    { id: 986, name: "アラブルタケ", types: ["grass", "dark"] },
    { id: 987, name: "ハバタクカミ", types: ["ghost", "fairy"] },
    { id: 988, name: "チヲハウハネ", types: ["fighting", "dragon"] },
    { id: 989, name: "スナノケガワ", types: ["water", "poison"] },
    { id: 990, name: "テツノワダチ", types: ["ground", "steel"] },
    { id: 991, name: "テツノツツミ", types: ["ice", "water"] },
    { id: 992, name: "テツノカイナ", types: ["electric", "fighting"] },
    { id: 993, name: "テツノコウベ", types: ["dark", "flying"] },
    { id: 994, name: "テツノドクガ", types: ["poison", "psychic"] },
    { id: 995, name: "テツノイバラ", types: ["rock", "electric"] },
    { id: 996, name: "セビエ", types: ["ice", "dragon"] },
    { id: 997, name: "セゴール", types: ["ice", "dragon"] },
    { id: 998, name: "セグレイブ", types: ["ice", "dragon"] },
    { id: 999, name: "コレクレー", types: ["ghost", "steel"] },
    { id: 1000, name: "サーフゴー", types: ["ghost", "steel"] },
    { id: 1001, name: "チオンジェン", types: ["dark", "grass"] },
    { id: 1002, name: "パオジアン", types: ["dark", "ice"] },
    { id: 1003, name: "ディンルー", types: ["dark", "ground"] },
    { id: 1004, name: "イーユイ", types: ["dark", "fire"] },
    { id: 1005, name: "トドロクツキ", types: ["dark", "dragon"] },
    { id: 1006, name: "テツノブジン", types: ["fighting", "water"] },
    { id: 1007, name: "コライドン", types: ["fighting", "dragon"] },
    { id: 1008, name: "ミライドン", types: ["electric", "dragon"] },
    { id: 1009, name: "ウネルミナモ", types: ["water", "dragon"] },
    { id: 1010, name: "テツノイサハ", types: ["rock", "flying"] }
];